### ISSUE TITLE
check runaway backtracking?

### ISSUE THREAD

**Issue by Aladdin-ADD** [BrainMaestro/eslint-plugin-optimize-regex#10]
for regex like `/(A+A+)+B/`, it can cause runaway backtracking. 

eg. `/(A+A+)+B/.test("AAAAAAAAAAA")` has a perf problem.

can we lint this?

**Comment by BrainMaestro** [comment]
Hey @Aladdin-ADD. This plugin just reports the possible optimizations from [regexp-tree](https://github.com/DmitrySoshnikov/regexp-tree). Does the actual repo handle this? If not, I think it should be discussed there because it seems quite useful.
