### ISSUE TITLE
Unexpected token {

### ISSUE THREAD

**Issue by rushsontakke** [BrainMaestro/eslint-plugin-optimize-regex#11]
Hi,
I have install optimize-regex plugin, but when I am adding optimize-regex plugin in my .eslintrc.js then I am facing below issue.

I am able to run other plugins like jasmine, unicorn, typelint in same .eslintrc.js file.

Unexpected token {
SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/vf-root/node_modules/eslint-plugin-optimize-regex/lib/index.js:9:21)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

**Comment by BrainMaestro** [comment]
Hi @rushsontakke, I'll take a look at this. What version of eslint are you using?

**Comment by rushsontakke** [comment]
Hi @BrainMaestro , I am using "eslint@4.6.1".
I am able to run other all plugins, but when I am adding optimize-regex in plugins array of .eslintrc.js, I am facing above issue.

**Comment by BrainMaestro** [comment]
Hey @rushsontakke, I have not been able to replicate this. Could you create a small repo that replicates this bug? You could also try updating your eslint

**Comment by rushsontakke** [comment]
Hi @BrainMaestro  
I have created below repo for same please try to validate
Thanks in advance.
https://github.com/rushsontakke/eslint-plugin-optimize-regex

**Comment by BrainMaestro** [comment]
can you also include a `package.json` in the repo so I can install the dependencies correctly

**Comment by rushsontakke** [comment]
Our project is not a node based utility, we are using eslint only for linting rules, so there is no package.json

**Comment by BrainMaestro** [comment]
Okay, how do you install the dependencies then? How was this plugin along with the others (including eslint) installed?

**Comment by rushsontakke** [comment]
we are installing globally eslint as dev dependency directly from node command prompt
npm install eslint --save-dev
and plugins also same
npm install --save-dev eslint-plugin-optimize-regex

**Comment by BrainMaestro** [comment]
I am still unable to replicate it. There's not much else I can do

**Comment by BrainMaestro** [comment]
I'll close this now since I can't offer any more assistance. If you are able to provide a repo that can reproduce this, then I will be happy to reopen.

**Comment by rushsontakke** [comment]
Hi @BrainMaestro 
I have added some test files in same repo 
https://github.com/rushsontakke/eslint-plugin-optimize-regex

Please try to do following steps you will get definitely same error.
1. Please install all plugins and eslint globally 
2. Use repositories .eslintrc.js filefor eslint config.
3. and run below command where you have put this .eslintrc.js file
./node_modules/.bin/eslint /home/rushi/Downloads/optimizeregex/eslint-plugin-optimize-regex/test
 
Please let me know if you need any additional information

**Comment by BrainMaestro** [comment]
Hi @rushsontakke. I can now replicate it. The error is actually because of the `eslint` and `eslint-plugin-optimize-regex` folders you have. Those folders cause npm to create a symlink instead of actually installing the dependency if you install from that directory. You can actually confirm this by looking at your global node_modules folder. The `eslint-plugin-optimize-regex` should be a symlink. This makes the global eslint to fail at finding the plugin.

The way to resolve this would be to get rid of both of those folders, uninstall them globally and reinstall them. That resolved it for me. Let me know if that fixes it for you.

**Comment by rushsontakke** [comment]
Hi,
I have tried with both with only local installation and with global also, but I am facing issue with only this plugin other all are working fine.
It will be great if you shared your local repo.

**Comment by BrainMaestro** [comment]
My local repo is the same as yours, I just deleted the `eslint-plugin-optimize-regex` folder and the `eslint` folder. Do that, uninstall with npm and reinstall

**Comment by rushsontakke** [comment]
Hi 
I got the solution, this error I am getting because I am using nodeJS version as 4.x.x so I have updated it to 6.x.x
so it is working fine.

Thanks for your help

**Comment by bdougherty** [comment]
@BrainMaestro would you be open to a pull request that adds node 4 compatibility? Would like to use this in [sindresorhus/xo](https://github.com/sindresorhus/xo) but can't because it requires node 4 support. I think it all it would take is removing the destructuring.

**Comment by BrainMaestro** [comment]
I don't mind. Can you do a PR?
