### ISSUE TITLE
Regex with 'u' flag and escaped special characters can't be parsed

### ISSUE THREAD

**Issue by regseb** [BrainMaestro/eslint-plugin-optimize-regex#23]
Hi,

Regex with unicode flag and some escaped special characters can't be parsed. For example this regex return "`/\./u can't be parsed: invalid Unicode escape \.`" error :

- `/\./u`
- `/\^/u`
- `/\$/u`
- `/\{/u`
- `/\}/u`
- `/\]/u`

The other special characters work (`*`, `+`, `?`, `(`, `)`, `|`, `[`, `\`).

**Comment by BrainMaestro** [comment]
Hi @regseb thanks for reporting the issue. It's a bit strange, but would you mind opening another one at [regexp-tree](https://github.com/DmitrySoshnikov/regexp-tree)? This plugin is just a frontend for the library. All the regex parsing logic is there. Once it gets fixed, I'll update the dependency

**Comment by regseb** [comment]
I open an issue on _regexp-tree_: https://github.com/DmitrySoshnikov/regexp-tree/issues/162

Thanks.

**Comment by BrainMaestro** [comment]
Hi @regseb thanks for that. I'll keep an eye on it

**Comment by BrainMaestro** [comment]
@regseb I will go ahead and close this now; since the upstream issue does not seem to have any activity
