### ISSUE TITLE
Wrong sorting/optimization

### ISSUE THREAD

**Issue by denisx** [BrainMaestro/eslint-plugin-optimize-regex#27]
`[^a-zа-яё -]+/gi`
wants to be
`[^ -a-zа-яё]+/gi`
then wants to be
`/[^ -azа-яё]+/gi`

**Comment by BrainMaestro** [comment]
Hi @denisx that's a bit strange. Would you mind creating a issueat https://github.com/DmitrySoshnikov/regexp-tree? That is what actually supplies the optimization suggestions. Thanks for reporting!

**Comment by BrainMaestro** [comment]
@denisx I'll close this now
