### ISSUE TITLE
Proposed optimization gives errors in code

### ISSUE THREAD

**Issue by dietergeerts** [BrainMaestro/eslint-plugin-optimize-regex#5]
I got following warning from the rule:

`/^.\// can be optimized to /^.//  optimize-regex/optimize-regex`

for this code:

`expect(Object.keys(paths).map(extractBaseUrl)).to.all.match(/^.\//);`

So when using the proposed optimized version, there is obviously an error, because the regex is inline, and not made with new RegExp and as string.

This is a bug for me, and the rule should check how the regex is being used.

**Comment by BrainMaestro** [comment]
Hey @dietergeerts. It's actually a bug in the [regexp-tree](https://github.com/DmitrySoshnikov/regexp-tree) library. I opened a [PR](https://github.com/DmitrySoshnikov/regexp-tree/pull/77) there to fix it. Once it's merged, I will update the plugin. 

Thanks for reporting this.

**Comment by BrainMaestro** [comment]
@dietergeerts v1.1.2 should have the fix. I'll close this now, but if it reoccurs, let me know

**Comment by dietergeerts** [comment]
Thx for the quick fix!
