### ISSUE TITLE
Can we get a new release?

### ISSUE THREAD

**Issue by RebeccaStevens** [BrainMaestro/eslint-plugin-optimize-regex#55]
The current latest version (v1.1.6) of this project has `regexp-tree@0.0.85` as a dependency which has `mem@1.1.0` in its dependency tree. `mem@1.1.0` has a vulnerability (WS-2018-0236) that is fixed in version `4.0.0`.

`mem` is no longer a dependency of newer versions of `regexp-tree` (including v0.1.11 which is currently used by this project's master branch)

**Comment by BrainMaestro** [comment]
Hi @RebeccaStevens, this kind of fell through the cracks. I will create a new release soon

**Comment by BrainMaestro** [comment]
Done! Let me know if something is missing

**Comment by diegocr** [comment]
What about ESLint 8.x ? sorry for hijacking this, but wondering if someone tested it and this plugin already works or not before we attempt on upgrading :)
