### ISSUE TITLE
Bad replacement: `/(_|[^\s\w])/g` => `/([\s\w])/g`

### ISSUE THREAD

**Issue by mikestopcontinues** [BrainMaestro/eslint-plugin-optimize-regex#57]
I filed this bug with: https://github.com/DmitrySoshnikov/regexp-tree

Here: https://github.com/DmitrySoshnikov/regexp-tree/issues/198

So this ticket is more to update the version number when the upstream bug gets closed.

Thanks!

**Comment by BrainMaestro** [comment]
Hi @mikestopcontinues thanks for reporting. The PR has been merged. Since it's a patch release, you should already be able to use it without me bumping the version right?

**Comment by mikestopcontinues** [comment]
Hi @BrainMaestro, you've got the version hard-set in package.json. Generally, I think that's better, but a caret might be better to prevent future updates. I would've made the PR, but I'm not sure which way you'd prefer.

**Comment by BrainMaestro** [comment]
I think a caret is better. I would welcome a PR for that
