### ISSUE TITLE
Join forces with eslint-plugin-unicorn

### ISSUE THREAD

**Issue by EvgenyOrekhov** [BrainMaestro/eslint-plugin-optimize-regex#59]
[eslint-plugin-unicorn](https://github.com/sindresorhus/eslint-plugin-unicorn) has the [regex-shorthand](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/master/docs/rules/regex-shorthand.md) rule, which, according to https://github.com/sindresorhus/eslint-plugin-unicorn/issues/473, has some advantages over eslint-plugin-optimize-regex.

eslint-plugin-unicorn also has another rule that works with regexes: [no-unsafe-regex](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/master/docs/rules/no-unsafe-regex.md).

As an ESLint user I'd rather have one plugin with multiple rules than many plugins that each have one rule.

So maybe you could join forces with eslint-plugin-unicorn and improve its regex-shorthand rule if you can, and then deprecate eslint-plugin-optimize-regex?

**Comment by brettz9** [comment]
@EvgenyOrekhov While I find unicorn to be a great library, with the mix-and-match capability of eslint configs, I personally think there is place for a separate plugin with some who may prefer the ability to only pick a rule they need.

Although I don't think the current plugin offers anything essentially different than Unicorn's `better-regex` rule in unicorn at present (and Unicorn also parses `new RegExp()` strings), my PR #60 here would allow one advantage over Unicorn of being able to whitelist or blacklist the underlying `regexp-tree` options. (Feel free to file an issue with Unicorn and ping me there so I can hopefully find time to file a PR if there is interest in adding this feature.)

**Comment by BrainMaestro** [comment]
I think it's fine to have this separate, and since it still has users, I will close this
