### ISSUE TITLE
`\.` should not be optimized to `.`

### ISSUE THREAD

**Issue by ckknight** [BrainMaestro/eslint-plugin-optimize-regex#6]
<img width="453" alt="screen shot 2017-07-07 at 9 55 54 am" src="https://user-images.githubusercontent.com/66227/27968114-90f1e376-62fa-11e7-9b6f-16ddab7f165f.png">

**Comment by BrainMaestro** [comment]
Hmm. The rules for optimization are actually defined in the regexp-tree repo. Would you mind reporting it there? I'll still take a look at this later. Thanks

**Comment by BrainMaestro** [comment]
I opened a PR in the [regexp-tree](https://github.com/DmitrySoshnikov/regexp-tree/pull/82) repo to fix this. Once it's merged I'll update the plugin.

**Comment by BrainMaestro** [comment]
@ckknight The bug should be fixed. Let me know if it works for you.
