### ISSUE TITLE
[bug] Invalid regular expression: missing /

### ISSUE THREAD

**Issue by Aladdin-ADD** [BrainMaestro/eslint-plugin-optimize-regex#8]
```diff
-newPath = pathname.replace(/[/\\]$/, "") + suffix;
+newPath = pathname.replace(/[/\]$/, "") + suffix;

```

**Comment by BrainMaestro** [comment]
Hey @Aladdin-ADD thanks for reporting this. I just opened an [issue](https://github.com/DmitrySoshnikov/regexp-tree/issues/83) on the regep-tree repo. Once it's fixed, I'll update the plugin.

**Comment by BrainMaestro** [comment]
I've updated the plugin with the fix. The problem should not occur anymore. Feel free to reopen it if that changes
